baseUrl: $PRIMARY_SITE_URL
enabled: true
handle: default
hasUrls: true
language: en-US
name: 'Brass Tacks Web'
primary: true
siteGroup: 019d8137-088c-4f8f-9662-d26ddd7f2fb7 # Morganton Day School
sortOrder: 1
