dateModified: 1715111966
email:
  fromEmail: trevor@brasstacksweb.com
  fromName: 'Morganton Day School'
  replyToEmail: null
  template: null
  transportSettings:
    messageStream: ''
    token: $POSTMARK_API_KEY
  transportType: craftcms\postmark\Adapter
meta:
  __names__:
    019d8137-088c-4f8f-9662-d26ddd7f2fb7: 'Brass Tacks Web' # Brass Tacks Web
    812fd012-9cc4-4c3c-bf03-845a6340a1f5: 'Brass Tacks Web' # Brass Tacks Web
plugins:
  postmark:
    edition: standard
    enabled: true
    schemaVersion: 2.0.1
system:
  edition: solo
  live: true
  name: 'Brass Tacks Web'
  retryDuration: null
  schemaVersion: 5.0.0.20
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  require2fa: false
  requireEmailVerification: true
